// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace CnSharp.VisualStudio.SharpUpdater
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string guidSharpUpdaterPackageString = "85ecc0d6-9c3a-432f-ac95-7a9583195cf5";
        public static Guid guidSharpUpdaterPackage = new Guid(guidSharpUpdaterPackageString);

        public const string guidProjectCmdSetString = "9065ee1d-60e4-44a1-9303-2679b24fa055";
        public static Guid guidProjectCmdSet = new Guid(guidProjectCmdSetString);

        public const string guidProjectAddCmdSetString = "307e403c-3431-45b9-86d6-3dff0810d838";
        public static Guid guidProjectAddCmdSet = new Guid(guidProjectAddCmdSetString);

        public const string guidImagesString = "d524bb98-8a0c-4aa9-95ea-87ece9af81f8";
        public static Guid guidImages = new Guid(guidImagesString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int ProjectMenuGroup = 0x1020;
        public const int SharpPackCommandId = 0x0100;
        public const int ProjectAddMenuGroup = 0x1020;
        public const int AddIgnoreFileCommandId = 0x0100;
        public const int AddManifestFileCommandId = 0x0101;
        public const int icon1 = 0x0001;
    }
}